version: 0.2

env:
  parameter-store:
    LOGIN_PASSWORD: dockerLoginPassword

phases:
  pre_build:
    commands:
      - "echo \"[requests]: pre-build\""
      - docker login –u appcypher –p $LOGIN_PASSWORD

  build:
    commands:
    - "echo \"[requests]: build\""
    - docker-compose -f docker/compose.yml up
    - docker-compose -f docker/compose.yml down

  post_build:
    commands:
      - "echo \"[requests]: post-build\""
      - docker tag docker_app appcypher/requests_app:latest
      - docker tag docker_server appcypher/requests_server:latest
      - docker login username="appcypher"
      - docker push appcypher/requests_server
      - docker push appcypher/requests_app
