version: 2
jobs:
  build:
    working_directory: ~/requests
    docker:
      - image: circleci/python:3.7.3 # Python base image
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: circleci/postgres:9.6.2 # Database image
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: requests_test
    steps:
      - checkout  # checkout source code to working directory
      # Reuse cache
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:  # Ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      # Install dependencies
      - run:
          command: |  # Install pipenv and install dependencies
            sudo pip install pipenv
            pipenv install --dev
      # Cache dependencies
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      # Run tests
      - run:
        command: |
          pipenv shell
          pytest
      # Upload coverage
      - run:
        command: |
          coverage
      # Upload test results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1



