version: 2
jobs:
  build:
    working_directory: ~/requests
    docker:
      # Python base image
      - image: circleci/python:3.7.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
          SQLALCHEMY_DATABASE_URI_TESTING: postgresql://localhost/requests_test
      # Database image
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: requests_test
    steps:
      # Checkout source to `working_directory`
      - checkout
      # Restore cache
      - restore_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      # Install pipenv dependencies. pipenv comes installed.
      - run:
          name: Installing dependencies
          command: |
            pipenv install --dev
      # Cache dependencies
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      # Creating mock resource
      - run:
          name: Creating mock resources
          command: |
            mkdir -p client/dist
            echo "function(){}" > client/dist/bundle.min.js
      # Run tests
      - run:
          name: Running tests
          command: |
            pipenv run pytest
      # Upload coverage
      - run:
          name: Reporting coverage
          command: |
            pipenv run coveralls
      # Upload test results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
