version: '3'
services:
  database:
    restart: always
    image: postgres:11.2
    environment:
      - POSTGRES_DB=requests
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    restart: always
    user: root
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    ports:
      - '5000:5000'
    expose:
      - '5000'
    depends_on:
      - database

  server:
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    expose:
      - '80'
    depends_on:
      - app
      - database

volumes:
  db-data:
